let student_alumni_list=[
    {
        student_alumni_name:"Pranit Patro",
        student_alumni_batch:"2017",
        student_alumni_course:"B.Tech",
        student_alumni_branch:"CSE",
        student_alumni_company_name:"Google",
        student_alumni_feedback:"The training at THE VITM prepared me for a successful career at Google. The hands-on experience and industry-ready skills helped me secure a job as a software engineer.",
        student_alumni_added_date:"25-11-2023",
        student_img_id:"1U3g0cjOK8-MR4mUHCicLXwpAPDNfkGqP",
    },
    {
        student_alumni_name:"Pradhan Dash",
        student_alumni_batch:"2019",
        student_alumni_course:"B.Tech",
        student_alumni_branch:"CSE",
        student_alumni_company_name:"JPMorgan Chase & Co.",
        student_alumni_feedback:"Thanks to THE VITM, I landed a position at Amazon. The faculty's guidance and the excellent campus placements helped me grow professionally and personally.",
        student_alumni_added_date:"25-11-2023",
        student_img_id:"1yvnwr4CtCIixr9GiuJuDKW7vu5HOiDbH",
    },
    {
        student_alumni_name:"Anuradha Tripathy",
        student_alumni_batch:"2018",
        student_alumni_course:"B.Tech",
        student_alumni_branch:"CSE",
        student_alumni_company_name:"TCS",
        student_alumni_feedback:"I received immense support from the placement cell, which helped me secure a job at Microsoft. The practical learning approach at THE VITM was crucial for my success.",
        student_alumni_added_date:"25-11-2023",
        student_img_id:"1_xhNDXQgJlPc-zRhzfUOegSEGToD1Lad",
    },
    {
        student_alumni_name:"Sunanda Mahapatra",
        student_alumni_batch:"2015",
        student_alumni_course:"B.Tech",
        student_alumni_branch:"CSE",
        student_alumni_company_name:" Cognizant",
        student_alumni_feedback:"THE VITM provided the right mix of theoretical knowledge and practical skills, which helped me land a position at IBM. The internship opportunities were vital.",
        student_alumni_added_date:"25-11-2023",
        student_img_id:"13gOkv45RV1wz_lvFtBJrnWqEn9-rgWBd",
    },
    {
        student_alumni_name:"Srikanta Panigrahy",
        student_alumni_batch:"2019",
        student_alumni_course:"B.Tech",
        student_alumni_branch:"CSE",
        student_alumni_company_name:" HP",
        student_alumni_feedback:"Being part of THE VITM made me confident enough to crack the interview at Apple. The comprehensive curriculum prepared me for real-world challenges.",
        student_alumni_added_date:"25-11-2023",
        student_img_id:"19gA7yx8sejkrJHssmzlUgcVuEwycCr7X",
    },
    {
        student_alumni_name:"Srinivash Panda",
        student_alumni_batch:"2021",
        student_alumni_course:"B.Tech",
        student_alumni_branch:"CSE",
        student_alumni_company_name:" Adobe",
        student_alumni_feedback:"I am proud to be an alumnus of THE VITM. The mentorship and skill-building programs helped me secure a role at Cisco",
        student_alumni_added_date:"25-11-2023",
        student_img_id:"1H4sGxkJmhE7i9nYC4WSnmDkffq9fFZ4Z",
    },
    {
        student_alumni_name:"Suraj Raulo",
        student_alumni_batch:"2023",
        student_alumni_course:"B.Tech",
        student_alumni_branch:"CSE",
        student_alumni_company_name:"Oracle",
        student_alumni_feedback:"THE VITM helped me develop both technical and soft skills, paving the way for my placement at Oracle. The campus placements were top-notch.",
        student_alumni_added_date:"25-11-2023",
        student_img_id:"1zu3LFTA0MJ9tNOMpaB2qSSrDtmcx3Kha",
    },
    {
        student_alumni_name:"Deepak Behera",
        student_alumni_batch:"2023",
        student_alumni_course:"B.Tech",
        student_alumni_branch:"CSE",
        student_alumni_company_name:" Amazon",
        student_alumni_feedback:"The exposure to real-world projects at THE VITM played a huge role in my success at Accenture. I'm grateful for the opportunities.",
        student_alumni_added_date:"25-11-2023",
        student_img_id:"19gA7yx8sejkrJHssmzlUgcVuEwycCr7X",
    },
    {
        student_alumni_name:"Alpha Padhy",
        student_alumni_batch:"2012",
        student_alumni_course:"B.Tech",
        student_alumni_branch:"CSE",
        student_alumni_company_name:" IBM",
        student_alumni_feedback:"THE VITM gave me the tools and knowledge to excel in my placement at TCS. Their constant support and preparation were key.",
        student_alumni_added_date:"25-11-2023",
        student_img_id:"1U3g0cjOK8-MR4mUHCicLXwpAPDNfkGqP",
    },
    

]

export {student_alumni_list};